# Generated by Django 6.1.1 on 2026-09-29 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL identifier. Keep this unchanged after publishing to preserve links.', max_length=200, unique=True)),
                ('summary', models.CharField(help_text='Short description for the index and search engines.', max_length=300)),
                ('body', models.TextField(help_text='Plain text. Separate paragraphs with a blank line; HTML is displayed as text.')),
                ('category', models.CharField(help_text='Use a consistent label, such as Python, Automation, or Applied Physics.', max_length=100)),
                ('published_date', models.DateField(default=django.utils.timezone.localdate, help_text='Published notes become visible on this date (site timezone).')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ['-published_date', '-created_date', '-pk'],
            },
        ),
    ]
