# Generated by Django 6.1.1 on 2026-09-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldnote',
            name='body',
            field=models.TextField(help_text='Markdown: ## headings, lists, **bold**, *italic*, > quotes, [text](URL), and fenced code with ```python. Separate paragraphs with a blank line. HTML is sanitized.'),
        ),
    ]
